version: "3.9"
services:
  # search:
  #   build:
  #     context: .
  #     dockerfile: search.Dockerfile
  #   image: twitter_search
  #   network_mode: host
  #   environment:
  #     - PYTHONUNBUFFERED=1
  stream:
    build:
      context: .
      dockerfile: stream.Dockerfile
    image: twitter_stream
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1