services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: website-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: website-client
    ports:
      - "3000:80"